# Generated by Django 5.1.2 on 2025-07-18 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='مكان التربيزة')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='رقم التربيزة')),
                ('capacity', models.PositiveIntegerField(verbose_name='عدد الكراسي المسموح بها')),
                ('status', models.CharField(choices=[('available', 'متاح'), ('occupied', 'مشغول'), ('reserved', 'محجوز'), ('maintenance', 'تحت الصيانة')], default='available', max_length=20)),
                ('qr_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='table.tablearea')),
            ],
            options={
                'unique_together': {('number', 'area')},
            },
        ),
    ]
