# Generated by Django 5.1.2 on 2025-07-21 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='qr_code',
        ),
    ]
