# Generated by Django 5.1.2 on 2025-07-25 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_jwt_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'مالك'), ('manager', 'مدير'), ('cashier', 'كاشير')], default='cashier', max_length=10, verbose_name='الوظيفة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='المشرف'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', regex='^[a-zA-Z0-9_]+( [a-zA-Z0-9_]+)*$')], verbose_name='اسم المستخدم'),
        ),
    ]
