# Generated by Django 5.1.2 on 2025-04-17 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Item Name')),
                ('unit', models.CharField(choices=[('Liter', 'L'), ('Kilogram', 'Kg'), ('Piece', 'Pcs'), ('Pack', 'Pck'), ('Bottle', 'Btl'), ('Gram', 'Gram'), ('Milliliter', 'ml')], max_length=12, verbose_name='Stock Unit')),
                ('quantity_in_stock', models.FloatField(default=0)),
                ('reorder_level', models.FloatField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='inventory.ingredient')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='menu.menuitemvariation')),
            ],
            options={
                'unique_together': {('variation', 'ingredient')},
            },
        ),
    ]
