# Generated by Django 5.1.2 on 2025-04-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='qty',
            new_name='quantity_required',
        ),
    ]
