# Generated by Django 5.1.2 on 2025-04-24 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_qty_recipeingredient_quantity_required'),
        ('menu', '0003_alter_menuitemvariation_variation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('variation', 'ingredient')},
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='menu.menuitemvariation'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('menu_item', 'ingredient'), ('variation', 'ingredient')},
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.CheckConstraint(condition=models.Q(('variation__isnull', False), ('menu_item__isnull', False), _connector='OR'), name='not_both_null'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.CheckConstraint(condition=models.Q(('variation__isnull', False), ('menu_item__isnull', False), _negated=True), name='not_both_not_null'),
        ),
    ]
