# Generated by Django 5.1.2 on 2025-07-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_recipeingredient_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تم إنشاؤه في'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_in_stock',
            field=models.FloatField(default=0, verbose_name='الكمية المتوفرة في المخزون'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='reorder_level',
            field=models.FloatField(default=0, verbose_name='مستوى إعادة الطلب'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('Liter', 'L'), ('Kilogram', 'Kg'), ('Piece', 'Pcs'), ('Pack', 'Pck'), ('Bottle', 'Btl'), ('Gram', 'Gram'), ('Milliliter', 'ml')], max_length=12, verbose_name='الوحدة'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تم التحديث في'),
        ),
    ]
