# Generated by Django 5.1.2 on 2025-04-17 16:51

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[350, 350], upload_to='images/category_image/')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('sku', models.CharField(blank=True, max_length=20, null=True)),
                ('visible', models.BooleanField(blank=True, default=True, null=True)),
                ('product_image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[700, 500], upload_to='images/product_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='menu.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[700, 500], upload_to='gallery/products/')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_gallery', to='menu.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value_type', models.CharField(blank=True, choices=[('radio', 'Radio'), ('checkbox', 'Checkbox')], max_length=20, null=True)),
                ('required', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_variation', to='menu.menuitem')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('item', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MenuItemVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('extra_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('label_image', models.ImageField(blank=True, null=True, upload_to='images/product_variation_image/')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variation_info', to='menu.variation')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('variation', 'value')},
            },
        ),
    ]
