# Generated by Django 5.1.2 on 2025-04-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemvariation',
            name='label_image',
        ),
    ]
