# Generated by Django 5.1.2 on 2025-04-24 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menuitemvariation_label_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemvariation',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_variation_info', to='menu.variation'),
        ),
    ]
