# Generated by Django 5.1.2 on 2025-07-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitemvariation_variation'),
        ('order', '0002_remove_order_items_remove_order_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_variations',
            field=models.ManyToManyField(blank=True, to='menu.menuitemvariation'),
        ),
    ]
