# Generated by Django 5.1.2 on 2025-07-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_cancelled_alter_orderitem_item_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='person_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
